global:
  region: australia-southeast1
  project_name: shorted
  environment: dev
  domain: shorted.com.au
function:
  name: watcher 
  description: watcher sources and detect collection events
  runtime: go113
  memory: 128
  triggerType: http
  entrypoint: Watch
  zipPath: ../../../index.zip
  public: true
  envVars:
  - name: LOGGING_ENCODER
    value: stackdriver
  # iam:
  #     serviceAccount:
  #       name: ..
  #       roles:
  #       - ..

  