global:
    region: australia-southeast1
    project_name: shorted
    environment: dev
    domain: shorted.com.au

iam:
    serviceAccounts:
        functions-admin:
            name: functions-admin
            keyAdmins:
            - user:ben@shorted.com.au
            roles:
            - roles/deploymentmanager.editor
            - roles/storage.admin
            - roles/logging.admin
            - roles/cloudfunctions.developer
            - roles/cloudfunctions.serviceAgent
            - roles/cloudfunctions.admin
            - roles/iam.serviceAccountUser
        collector:
            name: collector
            roles:
            - roles/cloudtrace.agent
        watcher:
            name: watcher
            roles:
            - roles/cloudtrace.agent
            - roles/storage.objectAdmin

gcs:
    buckets:
        stocks:
            name: stocks
            users:
                collector:
                    name: collector
                    members: {}
        watcher-index:
            name: watcher-index
            users:
                watcher:
                    name: watcher
                    members: {}
