version: '2.2'
services:
    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.2
        environment:
            SERVER_NAME: kibana.dev.nutry
            ELASTICSEARCH_URL: http://elasticsearch:9200
        volumes:
            - ${PWD}/config/kibana.yml:/usr/share/kibana/config/kibana.yml
        links:
            - elasticsearch
        ports:
            - 5601:5601
        networks:
            - esnet
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data
            - ${PWD}/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        ports:
            - 9200:9200
        networks:
            - esnet
    elasticsearch2:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        container_name: elasticsearch2
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - 'discovery.zen.ping.unicast.hosts=elasticsearch'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata2:/usr/share/elasticsearch/data
            - ${PWD}/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        networks:
            - esnet

volumes:
    esdata1:
        driver: local
    esdata2:
        driver: local

networks:
    esnet:
        driver: bridge
