resources:
  - type: storage.v1.bucket
    name: sls-ingestor-dev-1596719033969
  - type: 'gcp-types/cloudfunctions-v1:projects.locations.functions'
    name: ingestor-dev-first
    properties:
      parent: projects/shorted-dev-aba5688f/locations/australia-southeast1
      availableMemoryMb: 256
      runtime: go113
      timeout: 60s
      entryPoint: Hello
      function: ingestor-dev-first
      sourceArchiveUrl: >-
        gs://sls-ingestor-dev-1596719033969/serverless/ingestor/dev/1596722225202-2020-08-06T13:57:05.202Z/ingestor.zip
      labels: {}
      httpsTrigger:
        url: path
